# Generated by Django 5.0 on 2024-08-09 15:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_otherskill_skill_name_alter_skills_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='helkllo', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
