# Generated by Django 5.0 on 2024-01-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2024', '0003_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
