# Generated by Django 5.0 on 2024-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2024', '0004_project_featured_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_images',
            new_name='featured_image',
        ),
    ]
