# Generated by Django 5.0 on 2024-01-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2024', '0007_alter_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='prject',
            new_name='project',
        ),
    ]
