# Generated by Django 5.0 on 2024-08-09 15:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2024', '0012_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dm8tng2j0/image/upload/v1723218308/rvumjzxdt5tbjv4gycv1.jpg', max_length=255, verbose_name='image'),
        ),
    ]
